Доработана функциональность HistoryManager по техническому заданию спринта
H1dd3Nya/java-kanban pull request #2
Opened 2024-05-08 10:26 UTC by H1dd3Nya

2024-05-09 05:54 UTC, TomattmanYandex requested changes
Привет, комментов много, по сути задание не сделано почти

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +        nodes.remove(id);
публичный метод remove должен не только удалять, из мапы, но и удалять из связного списка

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +    private Node tail;
для связного списка гораздо важнее первая нода, потому что перебирают обычно с начала

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +    private Node tail;
точнее без первой ноды вывод будет или в обратном порядке, или займет гораздо больше времени, ибо надо перебрать до первой ноды и потом перебирать обратно до последней

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +    private Node tail;
поэтому в стандартной реализации этого проекта обычно в менеджере истории хранят первую и последнюю ноду, первую для быстроты вывода, последнюю, для скорости добавления

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +            remove(task.getId());
текущий метод remove удаляет только из мапы но не из связанного списка

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +        final Node oldTail = tail;
надо переделать с завязкой на то, что мы храним начало списка
также надо сделать метод на отлинковку, и вызывать его при удалении элемента

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +        List<Task> history = new ArrayList<>();
на получении истории надо использовать связный список, и вытягивать данные из него а не из мапы,
в текущей реализации связанный список вообще никак не задействован

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/history/Node.java
> +    private Node next;
есть 3 переменные геттеры или сеттеры есть только на две, как ибудет использваны все три - непонятно, но это будет исправлено с исправлением функционала менеджера истории

2024-05-09 05:54 UTC, TomattmanYandex commented on src/manager/task/InMemoryTaskManager.java
> +        historyManager.remove(id);
еще стоит удалять при ошищениии списка всех тасков, или сабтасков, или эпиков

2024-05-09 05:54 UTC, TomattmanYandex commented on test/manager/history/InMemoryHistoryManagerTest.java
> +    private static final HistoryManager historyManager = Managers.getDefaultHistory();
так как мы тестируем тут конкретную реализацию, лучше создавать через конструктор, мало ли Managers.getDefaultHistory(); вернет нам какую то другую имплементацию

2024-05-15 09:06 UTC, H1dd3Nya commented
Саша, спасибо за ревью!
Я не сразу понял, как реализовать ТЗ, но благодаря твоим комментариям и вебинару, вроде, все получилось, спасибо!

2024-05-15 12:43 UTC, TomattmanYandex requested changes
Привет, надо почистить закоментированный код, ну и есть одна мелочь, ее можно поправить

2024-05-15 12:43 UTC, TomattmanYandex commented on src/Main.java
> +//        Task task1 = new Task("Task 1", "Task 1");
закомментированный код не допускается

2024-05-15 12:43 UTC, TomattmanYandex commented on src/manager/history/InMemoryHistoryManager.java
> +    private Node head = new Node(null, null, null);
зачем создавать так?
теперь чтобы понять пустая это нода, надо обратиться к ней, потом к обьекту внутри, а раньше можно было просто head == null

2024-05-17 07:25 UTC, TomattmanYandex approved these changes
ПРинято

2024-05-17 07:30 UTC, merged