Solution for sprint 7
H1dd3Nya/java-kanban pull request #3
Opened 2024-06-09 16:21 UTC by H1dd3Nya

2024-06-10 11:01 UTC, TomattmanYandex requested changes
Комменты в коде

2024-06-10 11:01 UTC, TomattmanYandex commented on src/manager/Managers.java
> +    public static FileBackedTaskManager getDefaultFile(Path path) {
дефолтный один
этот метод стоит назвать getFileBackedTaskManager

2024-06-10 11:01 UTC, TomattmanYandex commented on src/model/Task.java
> +    public Integer getEpicId() {
У таска нету эпика, следовательно этот метод тут не должен присутствовать

2024-06-10 11:01 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +    private void loadDataFromFile() {
После выполнения этого метода, эпики будут с пустым списком сабтасков

2024-06-10 11:01 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +    public String toString(Task task) {
этот метод должен быть приватным

2024-06-10 11:01 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +    public String toString(Task task) {
а вообще было бы удобно иметь класс конвертер , который умеет преобразовывать таск в строку и обратно и чтобы эти методы были там

2024-06-10 11:01 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +    public String toString(Task task) {
и еще момент, я бы рекомендовал не называть методы как стандартные методы класса object ибо это может запутать

2024-06-10 11:01 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +        try {
почему бы вместо try catch не проверить значение элемента в начале?

2024-06-10 11:01 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +    public List<Task> getAllTasks() {
не надо переопределять метод , если там нету изменений в поведении
переопределять нужно только те, которые как то работают по другому

2024-06-10 11:01 UTC, TomattmanYandex commented on test/manager/file/FileBackedTaskManagerTest.java
> +        task = manager.createTask(new Task("Test", "Test", Status.NEW));
не уверен что хорошая идея по умолчанию добавлять какие то данные 
лучше работать с пустым хранилищем, и еслидля теста надо что то в нем, то добавлять в начале теста
так не получится ситуация, когда ты не понимаешь откуда данные есть в хранилище в самом начале тестового метода

2024-06-10 14:13 UTC, H1dd3Nya commented
Саша, привет!
Спасибо за работу и полезные комментарии. 
Использовал перегрузку вместо наследования метода getEpicId в Task, это правильно?
И нам на вебинаре предложили вариант именно с использованием наследования метода getEpicId от Task, почему так не правильно?

2024-06-10 15:35 UTC, TomattmanYandex approved these changes
Чуть чуть еще подправить
ПО поводу комента, да перегрузка лучше
не понимаю почему вам так обьясняли, ибо это противоречит многим принципам

2024-06-10 15:35 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +            return;
Странный момент, по условию надо было отловить IOExceptionи пробросить ManagerSaveException

2024-06-10 15:35 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +                    for (Subtask subtask : subTasks.values()) {
лучше сделать это после того как все будет считано, будет только один раз пройден цикл

2024-06-11 12:28 UTC, TomattmanYandex approved these changes
Прннято

2024-06-11 12:28 UTC, TomattmanYandex commented on src/manager/file/FileBackedTaskManager.java
> +            addSubTask(subtask);
как то усложенено, а еще статус эпика хранится в файле, можно было не пересчитывать,

2024-06-12 18:50 UTC, merged